"""
CrewAI Blog Generator Example

This is a placeholder script. Replace with your actual CrewAI implementation.

Expected Input (JSON via command line argument):
{
  "prompt": "Write a blog post about...",
  "title": "Optional title",
  "locale": "ko" or "en",
  "tags": ["tag1", "tag2"]
}

Expected Output (JSON to stdout):
{
  "title": "Generated Blog Title",
  "content": "Full blog post content in Markdown",
  "excerpt": "Short summary",
  "metadata": {}
}
"""

import sys
import json


def generate_blog_post(prompt: str, title: str = None, locale: str = "ko", tags: list = None):
    """
    Generate a blog post using CrewAI.
    
    Replace this function with your actual CrewAI crew setup.
    """
    # TODO: Implement your CrewAI crew here
    # Example:
    # from crewai import Agent, Task, Crew
    # 
    # writer = Agent(
    #     role='Blog Writer',
    #     goal='Write engaging blog posts',
    #     backstory='...'
    # )
    # 
    # task = Task(
    #     description=prompt,
    #     agent=writer
    # )
    # 
    # crew = Crew(agents=[writer], tasks=[task])
    # result = crew.kickoff()
    
    # Placeholder response
    return {
        "title": title or "AI Generated Blog Post",
        "content": f"# {title or 'AI Generated Blog Post'}\n\n{prompt}\n\n[Content generated by CrewAI would appear here]",
        "excerpt": f"This post was generated based on: {prompt[:100]}...",
        "metadata": {
            "locale": locale,
            "tags": tags or [],
            "generator": "crewai"
        }
    }


def main():
    if len(sys.argv) < 2:
        print(json.dumps({
            "error": "No input provided. Usage: python blog_generator.py '<json_input>'"
        }))
        sys.exit(1)
    
    try:
        # Parse input JSON from command line
        input_data = json.loads(sys.argv[1])
        
        prompt = input_data.get("prompt")
        title = input_data.get("title")
        locale = input_data.get("locale", "ko")
        tags = input_data.get("tags", [])
        
        if not prompt:
            print(json.dumps({"error": "Prompt is required"}))
            sys.exit(1)
        
        # Generate blog post
        result = generate_blog_post(prompt, title, locale, tags)
        
        # Output result as JSON
        print(json.dumps(result, ensure_ascii=False))
        
    except json.JSONDecodeError as e:
        print(json.dumps({"error": f"Invalid JSON input: {str(e)}"}))
        sys.exit(1)
    except Exception as e:
        print(json.dumps({"error": f"Generation failed: {str(e)}"}))
        sys.exit(1)


if __name__ == "__main__":
    main()
